# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_huntabyte-bitsui.ipynb.

# %% auto 0
__all__ = ['logger', 'build', 'source', 'commit', 'clone_dir', 'static_dir', 'tree', 'processed_tree']

# %% ../nbs/12_huntabyte-bitsui.ipynb 3
from .settings import settings, GitSource

from lovely_docs.docs import (
    build_markdown_doc_tree,
    process_tree_depth_first,
    calculate_total_usage,
    calculate_cost,
    save_processed_documents
)
import shutil
from pathlib import Path
import logging
import subprocess
import os

from .git import clone_repo

# %% ../nbs/12_huntabyte-bitsui.ipynb 4
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# %% ../nbs/12_huntabyte-bitsui.ipynb 7
build = True

source = GitSource(
    name="huntabyte/bitsui",
    doc_dir="docs/static/docs",
    repo="git@github.com:xl0/bits-ui.git",
    commit="better-llms-txt",
    ecosystems=["svelte"])

commit, clone_dir = clone_repo(source)
source.commit = commit # Replace the literal commit (master) with the hash

# %% ../nbs/12_huntabyte-bitsui.ipynb 9
# Recursively copy all .txt files in docs/static to corresponding .md files
static_dir = clone_dir / "docs" / "static" / "docs"
for txt_file in static_dir.rglob("*.txt"):
    md_file = txt_file.with_suffix(".md")
    md_file.parent.mkdir(parents=True, exist_ok=True)
    # logger.debug(f"{txt_file} -> {md_file}")
    shutil.copy(txt_file, md_file)

os.remove(clone_dir / "docs" / "static" / "docs"/ "llms.md")

# %% ../nbs/12_huntabyte-bitsui.ipynb 10
tree = build_markdown_doc_tree(clone_dir/source.doc_dir)

# %% ../nbs/12_huntabyte-bitsui.ipynb 16
processed_tree = await process_tree_depth_first(settings, tree, source.name)

# %% ../nbs/12_huntabyte-bitsui.ipynb 20
save_processed_documents(source, settings.output_dir / source.name.replace("/", "_"), processed_tree)
