# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_huntabyte-shadcn-svelte.ipynb.

# %% auto 0
__all__ = ['logger', 'build', 'source', 'commit', 'clone_dir']

# %% ../nbs/12_huntabyte-shadcn-svelte.ipynb 3
from .settings import settings, GitSource

from lovely_docs.docs import (
    build_markdown_doc_tree,
    process_tree_depth_first,
    calculate_total_usage,
    calculate_cost,
    save_processed_documents
)
from pathlib import Path
import logging
import subprocess

from .git import clone_repo

# %% ../nbs/12_huntabyte-shadcn-svelte.ipynb 4
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# %% ../nbs/12_huntabyte-shadcn-svelte.ipynb 6
build = True

source = GitSource(
    name="huntabyte/shadcn-svelte",
    doc_dir="docs/.svelte-kit/cloudflare/docs",
    repo="https://github.com/huntabyte/shadcn-svelte",
    commit="main")

commit, clone_dir = clone_repo(source)
source.commit = commit # Replace the literal commit (master) with the hash
