# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/11_sveltejs-sveltekit.ipynb.

# %% auto 0
__all__ = ['logger', 'source', 'commit', 'clone_dir']

# %% ../nbs/11_sveltejs-sveltekit.ipynb 3
from .settings import settings, GitSource
from .git import clone_repo
from lovely_docs.docs import (
    build_markdown_doc_tree,
    process_tree_depth_first,
    calculate_total_usage,
    calculate_cost,
    save_processed_documents
)
import llm
from llm.models import Usage
import anthropic
from pydantic import BaseModel, Field
from jinja2 import Environment, FileSystemLoader
import asyncio
import json
import shutil
from pathlib import Path
import langsmith as ls
import logging

# %% ../nbs/11_sveltejs-sveltekit.ipynb 4
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# %% ../nbs/11_sveltejs-sveltekit.ipynb 6
source = settings.sources["sveltejs/sveltekit"]
assert isinstance(source, GitSource)

commit, clone_dir = clone_repo(source)
source.commit = commit # Replace the literal commit (master) with the hash
